from pico2d import *
os.getcwd()
os.chdir('c:\\Users\\user\\Desktop\\tcu\\2-2\\2DGP\\2DProject')
open_canvas()
player_run1 = load_image('Asset1\\artwork\\Sprites\\player\\run\\player-run-1.png')
player_run2 = load_image('Asset1\\artwork\\Sprites\\player\\run\\player-run-2.png')
player_run3 = load_image('Asset1\\artwork\\Sprites\\player\\run\\player-run-3.png')
player_run4 = load_image('Asset1\\artwork\\Sprites\\player\\run\\player-run-4.png')
player_run5 = load_image('Asset1\\artwork\\Sprites\\player\\run\\player-run-5.png')
player_run6 = load_image('Asset1\\artwork\\Sprites\\player\\run\\player-run-6.png')
player_jump1 = load_image('Asset1\\artwork\\Sprites\\player\\jump\\player-jump-1.png')
player_jump2 = load_image('Asset1\\artwork\\Sprites\\player\\jump\\player-jump-2.png')
def player_run():
    clear_canvas_now()
    player_run1.draw_now(400,300)
    delay(0.08)
    clear_canvas_now()
    player_run2.draw_now(400,300)
    delay(0.08)
    clear_canvas_now()
    player_run3.draw_now(400,300)
    delay(0.08)
    clear_canvas_now()
    player_run4.draw_now(400,300)
    delay(0.08)
    clear_canvas_now()
    player_run5.draw_now(400,300)
    delay(0.08)
    clear_canvas_now()
    player_run6.draw_now(400,300)
    delay(0.08)

def player_jump():
    clear_canvas_now()
    player_jump1.draw_now(400,300)
    delay(0.06)
    clear_canvas_now()
    player_jump1.draw_now(400,310)
    delay(0.06)
    clear_canvas_now()
    player_jump1.draw_now(400,320)
    delay(0.06)
    clear_canvas_now()
    player_jump2.draw_now(400,310)
    delay(0.06)
    clear_canvas_now()
    player_jump2.draw_now(400,300)
    delay(0.02)

for a in range(10):
    player_run()
player_jump()
for a in range(10):
    player_run()
delay(5)
close_canvas()